# Generated by Django 5.0.6 on 2024-05-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ustoz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=225)),
                ("last_name", models.CharField(max_length=222)),
                ("picture", models.ImageField(upload_to="ustoz_images/")),
                ("birth_date", models.DateField()),
                ("birth_city", models.CharField(max_length=222)),
                ("likes", models.CharField(blank=True, max_length=222, null=True)),
                ("dislikes", models.CharField(blank=True, max_length=222, null=True)),
                ("currently", models.TextField(blank=True, null=True)),
                ("worries", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ustoz",
                "db_table": "Ustoz",
            },
        ),
    ]
