# Generated by Django 5.0.6 on 2024-06-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message1',
        ),
    ]
