# Generated by Django 5.0.6 on 2024-05-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsteacher",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
    ]
