# Generated by Django 5.0.6 on 2024-05-31 17:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_pages", "0002_alter_newsteacher_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="dars",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="dars_videos/"),
        ),
        migrations.AlterField(
            model_name="dars",
            name="video_url",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
