# Generated by Django 5.0.6 on 2024-05-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_pages", "0003_dars_video_alter_dars_video_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bitriuvchilar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mudat", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("image", models.ImageField(upload_to="Biturivchilar/images")),
            ],
        ),
    ]
