# Generated by Django 5.0.6 on 2024-06-01 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_pages", "0004_bitriuvchilar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dars",
            name="likes",
            field=models.ManyToManyField(
                related_name="post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
