# Generated by Django 5.0.6 on 2024-06-02 03:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_pages",
            "0006_alter_comment_options_rename_comment_comment_content_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dars",
            name="additions",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
