# Generated by Django 5.0.6 on 2024-06-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_pages", "0007_dars_additions"),
    ]

    operations = [
        migrations.AddField(
            model_name="dars",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
